[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "3.2.3"
rocket = { version = "0.5.1", features = ["json"] }
rocket_db_pools = { version = "0.2.0", features = ["mongodb"] }