GET http://127.0.0.1:8000/proveedores/get HTTP/1.1

Content-Type: application/json

###

POST http://127.0.0.1:8000/proveedores/add HTTP/1.1
Content-Type: application/json

{
    "email": "glquimbayor@gmail.com",
    "nome": "Gabriel Quimbayo",
    "codigos": []
}